[[plugins]]
repo = 'fatih/vim-go'
rev = 'v1.20'
on_ft = ['go']

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'twig', 'php']

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql', 'graphqls', '.gql']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['ts', 'tsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['pac', 'html', 'twig', 'php', 'js']

[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft = ['jsx']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'tfvars', 'tfstate']

