[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'twig', 'php']

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js', 'pac', 'html', 'twig', 'php']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'tpope/vim-fugitive'
